DROP TABLE IF EXISTS venda_item;
DROP TABLE IF EXISTS venda;
DROP TABLE IF EXISTS produto_servico;
DROP TABLE IF EXISTS funcionario;

DROP TABLE IF EXISTS midia;

DROP TABLE IF EXISTS chapa;
DROP TABLE IF EXISTS bloco;

DROP TABLE IF EXISTS endereco;
DROP TABLE IF EXISTS cliente;

DROP TABLE IF EXISTS admin;

